### ISSUE TITLE
question for waveform of strings

### ISSUE THREAD

**Issue by iljabek** [mdavidsaver/pyDevSup#10]
I've defined a waveform, with FTVL="STRING".
having a string array `["P1", "A1"]`, I'm getting an error `invalid literal for int() with base 10: 'P'` if trying to assign to e.g. `rec.field("VAL").getarray()[0]`

noticed the entry https://github.com/mdavidsaver/pyDevSup/blob/44e5bd98b9bf2516585da6fcd844a68d36a3311c/devsupApp/src/dbfield.c#L22

Shouldn't it be NPY_STRING?

with this in place, my ugly workaround at the moment looks like this:
```
            rec.field("VAL").putarraylen(len(recval))       
            arr = rec.field("VAL").getarray() # create alias
            for i,v in enumerate(recval):      
                for o,c in enumerate(v):      
                    arr[i][o] = c                 
 ```
is there a better method/example how to handle string waveforms?
Cheers!

**Comment by eltos** [comment]
In addition to using `NPY_STRING` instead of `NPY_BYTE` we could drop the 2D array creation in [dbfield.c#L90-L94](https://github.com/mdavidsaver/pyDevSup/blob/44e5bd98b9bf2516585da6fcd844a68d36a3311c/devsupApp/src/dbfield.c#L90-L94) and instead specify `desc->elsize = MAX_STRING_SIZE` after [line 96](https://github.com/mdavidsaver/pyDevSup/blob/44e5bd98b9bf2516585da6fcd844a68d36a3311c/devsupApp/src/dbfield.c#L96) like this:

Using this approach, numpy arrays in python will look like `[b'test' b'string' b'array' b'' b'']` instead of binary char integers `[[116 101 115 116 0 0 0 0 0...],[...]]` and item assignment also works fine.

This will however break existing implementations working with string waveforms.




_Modified dbf2np_map definition and build_array function from file `devsupApp/src/dbfield.c` for reference:_
```c
#ifdef HAVE_NUMPY
static const int dbf2np_map[DBF_MENU+1] = {
    NPY_STRING,  // DBF_STRING
    NPY_BYTE,    // DBF_CHAR
    NPY_UBYTE,   // DBF_UCHAR
    NPY_INT16,   // DBF_SHORT
    NPY_UINT16,  // DBF_USHORT
    NPY_INT32,   // DBF_LONG
    NPY_UINT32,  // DBF_ULONG
    NPY_FLOAT32, // DBF_FLOAT
    NPY_FLOAT64, // DBF_DOUBLE
    NPY_INT16,   // DBF_ENUM
    NPY_INT16,   // DBF_MENU
};
static PyArray_Descr* dbf2np[DBF_MENU+1];
#endif



static PyObject* build_array(PyObject* obj, void *data, unsigned short ftype, unsigned long nelem, int flags)
{
#ifdef HAVE_NUMPY
    PyArray_Descr *desc;
    int ndims = 1;
    npy_intp dims[1] = {nelem};

    if(ftype>DBF_MENU) {
        PyErr_SetString(PyExc_TypeError, "Can not map field type to numpy type");
        return NULL;
    }

    desc = dbf2np[ftype];
    if(ftype==DBF_STRING) {
        desc->elsize = MAX_STRING_SIZE;
    }

    Py_XINCREF(desc);
    return PyArray_NewFromDescr(&PyArray_Type, desc, ndims, dims, NULL, data, flags, (PyObject*)obj);
#else
    PyErr_SetNone(PyExc_NotImplementedError);
    return NULL;
#endif
}

```

**Comment by mdavidsaver** [comment]
> This will however break existing implementations working with string waveforms.

Array of DBF_STRING is a bit of a corner case in general, and the existing support here was a bit of an after thought on my part.

> we could drop the 2D array creation in [dbfield.c#L90-L94](https://github.com/mdavidsaver/pyDevSup/blob/44e5bd98b9bf2516585da6fcd844a68d36a3311c/devsupApp/src/dbfield.c#L90-L94) and instead specify `desc->elsize = MAX_STRING_SIZE`

This seems like a nicer solution (wish I had known about this).  @iljabek would this work better for you?

**Comment by iljabek** [comment]
@mdavidsaver @eltos, had a quick test, this works perfectly for me.
`rec.field("VAL").getarray().flat = valarray` becomes possible and consistent with scalar data types.

**Comment by iljabek** [comment]
@eltos, will you submit the pull request?
